version: '3.8'

services:
  eventstore:
    image: eventstore/eventstore:21.2.0-buster-slim
    command: --insecure --run-projections=All
    ports:
      - 2113:2113

  app:
    image: elixir:1.12.1
    depends_on:
    - eventstore
    environment:
    - 'ERL_AFLAGS=-kernel shell_history enabled'
    - EVENTSTORE_HOST=eventstore
    volumes:
    - ./:/app
    working_dir: /app
    command: tail -f /dev/null
